version: '3.4'

services:
  unicomi:
    image: unicomi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - 27018:27017
    volumes:
      - data:/data/db

volumes:
  data:
